"""
Dutch Vocab Audio Generator
============================
Reads a CSV of Dutch vocabulary, generates MP3 pronunciation files
using Google TTS, and builds a formatted Obsidian Vocabs.md.

SETUP (run once in Terminal):
    pip install gTTS

USAGE:
    python generate_vocab.py

    Place your CSV file at:  DutchA2/vocab_input.csv
    Audio files go to:       DutchA2/audio/
    Vocab note is written to: DutchA2/Vocabs.md

CSV FORMAT (see vocab_template.csv):
    dutch, english, category, example_dutch, example_english
    - dutch          : Dutch word or phrase  [required]
    - english        : English translation   [required]
    - category       : e.g. Work, Daily Life [optional]
    - example_dutch  : example sentence      [optional]
    - example_english: translation of example[optional]

HOW TO EXPORT FROM BUSUU:
    1. Log in at busuu.com → go to your Review/Vocabulary page
    2. Open browser DevTools (F12 or Cmd+Option+J on Mac)
    3. Go to the Console tab
    4. Paste and run the script from:
       https://github.com/joeperpetua/exportVocabBusuu
    5. Copy the output into a CSV file with the columns above
"""

import csv
import os
import re
from pathlib import Path
from collections import defaultdict

# ── Config ────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).parent
CSV_FILE     = SCRIPT_DIR / "vocab_input.csv"          # your exported vocab
AUDIO_DIR    = SCRIPT_DIR / "audio"                    # where MP3s are saved
OUTPUT_MD    = SCRIPT_DIR / "Vocabs.md"                # Obsidian note output
VAULT_AUDIO  = "DutchA2/audio"                         # path as seen by Obsidian

# ── Helpers ───────────────────────────────────────────────────────────────────

def safe_filename(word: str) -> str:
    """Turn a Dutch word/phrase into a safe filename."""
    name = word.lower().strip()
    name = re.sub(r"[^\w\s-]", "", name)
    name = re.sub(r"\s+", "_", name)
    return name + ".mp3"


def generate_audio(word: str, filepath: Path) -> bool:
    """Generate a Dutch TTS MP3 for a single word. Returns True on success."""
    try:
        from gtts import gTTS
        tts = gTTS(text=word, lang="nl", slow=False)
        tts.save(str(filepath))
        print(f"  ✅ {word}")
        return True
    except ImportError:
        print("  ❌ gTTS not installed. Run: pip install gTTS")
        return False
    except Exception as e:
        print(f"  ⚠️  Could not generate audio for '{word}': {e}")
        return False


def build_markdown(entries_by_category: dict) -> str:
    """Build the full Obsidian Vocabs.md content as a compact table."""

    total = sum(len(v) for v in entries_by_category.values())
    lines = []

    lines.append("# Dutch Vocabulary\n")
    lines.append(f"> [!tip] {total} words\n")
    lines.append("---\n")

    for category, entries in sorted(entries_by_category.items()):
        lines.append(f"## {category}\n")
        lines.append("| Dutch | Audio | English | Example |")
        lines.append("|-------|-------|---------|---------|")

        for e in sorted(entries, key=lambda x: x["dutch"].lower()):
            dutch      = e["dutch"]
            english    = e["english"]
            audio_file = e["audio_file"]
            ex_nl      = e.get("example_dutch", "").strip()
            ex_en      = e.get("example_english", "").strip()

            audio_cell   = f"![[{VAULT_AUDIO}/{audio_file}]]"
            example_cell = f"*{ex_nl}* — {ex_en}" if ex_nl and ex_en else (f"*{ex_nl}*" if ex_nl else "")

            # Escape pipe characters inside cell content
            dutch   = dutch.replace("|", "\\|")
            english = english.replace("|", "\\|")
            example_cell = example_cell.replace("|", "\\|")

            lines.append(f"| **{dutch}** | {audio_cell} | {english} | {example_cell} |")

        lines.append("")

    lines.append("<!-- Auto-generated by generate_vocab.py — do not edit manually -->")
    return "\n".join(lines)

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not CSV_FILE.exists():
        print(f"❌ CSV not found at: {CSV_FILE}")
        print("   Rename your exported file to 'vocab_input.csv' and place it next to this script.")
        return

    AUDIO_DIR.mkdir(exist_ok=True)

    entries_by_category = defaultdict(list)
    skipped = 0

    print(f"\n📖 Reading {CSV_FILE.name} ...")

    with open(CSV_FILE, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print(f"   Found {len(rows)} words\n🔊 Generating audio files ...\n")

    for row in rows:
        dutch   = row.get("dutch", "").strip()
        english = row.get("english", "").strip()

        if not dutch or not english:
            skipped += 1
            continue

        category   = row.get("category", "General").strip() or "General"
        audio_name = safe_filename(dutch)
        audio_path = AUDIO_DIR / audio_name

        # Only generate if file doesn't already exist
        if not audio_path.exists():
            success = generate_audio(dutch, audio_path)
            if not success:
                skipped += 1
                continue
        else:
            print(f"  ⏭️  {dutch} (already exists)")

        entries_by_category[category].append({
            "dutch":           dutch,
            "english":         english,
            "audio_file":      audio_name,
            "example_dutch":   row.get("example_dutch", ""),
            "example_english": row.get("example_english", ""),
        })

    print(f"\n📝 Writing {OUTPUT_MD.name} ...")
    md_content = build_markdown(entries_by_category)

    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write(md_content)

    total = sum(len(v) for v in entries_by_category.values())
    print(f"\n✅ Done!")
    print(f"   {total} words processed, {skipped} skipped")
    print(f"   Audio → {AUDIO_DIR}")
    print(f"   Note  → {OUTPUT_MD}")


if __name__ == "__main__":
    main()
